/**
 * CICDGenerator.ts — Phase 19 Step 19.5
 * Generate CI/CD pipeline configurations
 */

import { ProjectStack, CICDPipeline, DevOpsGenerationResult } from './DevOpsTypes';

export class CICDGenerator {
  generate(stack: ProjectStack, provider?: string): DevOpsGenerationResult {
    const ciProvider = provider || stack.existingCI || 'github-actions';
    const files: { name: string; content: string }[] = [];

    switch (ciProvider) {
      case 'github-actions':
        files.push({ name: '.github/workflows/ci.yml', content: this.githubActions(stack) });
        break;
      case 'gitlab-ci':
        files.push({ name: '.gitlab-ci.yml', content: this.gitlabCI(stack) });
        break;
      default:
        files.push({ name: '.github/workflows/ci.yml', content: this.githubActions(stack) });
    }

    return { type: 'ci', files, recommendations: [] };
  }

  private githubActions(stack: ProjectStack): string {
    const runtime = stack.runtime;
    const pm = stack.packageManager;

    if (runtime === 'node') return this.githubActionsNode(stack, pm);
    if (runtime === 'python') return this.githubActionsPython(stack);
    if (runtime === 'go') return this.githubActionsGo(stack);
    if (runtime === 'rust') return this.githubActionsRust(stack);
    return this.githubActionsGeneric(stack);
  }

  private githubActionsNode(stack: ProjectStack, pm: string): string {
    const install = pm === 'pnpm' ? 'pnpm install --frozen-lockfile' : pm === 'yarn' ? 'yarn install --frozen-lockfile' : 'npm ci';
    const setupPm = pm === 'pnpm' ? '\n      - uses: pnpm/action-setup@v4\n        with:\n          version: 9' : '';
    const lint = `${pm === 'pnpm' ? 'pnpm' : pm === 'yarn' ? 'yarn' : 'npm run'} lint`;
    const test = `${pm === 'pnpm' ? 'pnpm' : pm === 'yarn' ? 'yarn' : 'npm'} test -- --coverage`;
    const build = `${pm === 'pnpm' ? 'pnpm' : pm === 'yarn' ? 'yarn' : 'npm run'} build`;

    return `# Generated by INA-7 Pro DevOps Agent
name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

concurrency:
  group: \${{ github.workflow }}-\${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: ${pm}${setupPm}
      - run: ${install}
      - run: ${lint}

  test:
    runs-on: ubuntu-latest
    needs: lint${stack.databases.includes('postgres') ? '\n    services:\n      postgres:\n        image: postgres:16-alpine\n        env:\n          POSTGRES_DB: test\n          POSTGRES_PASSWORD: test\n        ports: ["5432:5432"]\n        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5' : ''}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: ${pm}${setupPm}
      - run: ${install}
      - run: ${test}
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage
          path: coverage/

  security:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: ${pm}${setupPm}
      - run: ${install}
      - run: npm audit --audit-level=high || true

  build:
    runs-on: ubuntu-latest
    needs: [test, security]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: ${pm}${setupPm}
      - run: ${install}
      - run: ${build}
      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: ${stack.framework === 'next' ? '.next/' : 'dist/'}

  docker:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          push: false
          tags: app:\${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
`;
  }

  private githubActionsPython(stack: ProjectStack): string {
    return `name: CI/CD Pipeline
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: \${{ matrix.python-version }}
          cache: pip
      - run: pip install -r requirements.txt
      - run: pip install pytest pytest-cov ruff
      - run: ruff check .
      - run: pytest --cov --cov-report=xml
`;
  }

  private githubActionsGo(stack: ProjectStack): string {
    return `name: CI/CD Pipeline
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - run: go vet ./...
      - run: go test -race -coverprofile=coverage.out ./...
      - run: go build -ldflags="-s -w" -o app .
`;
  }

  private githubActionsRust(stack: ProjectStack): string {
    return `name: CI/CD Pipeline
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v2
      - run: cargo fmt --check
      - run: cargo clippy -- -D warnings
      - run: cargo test
      - run: cargo build --release
`;
  }

  private githubActionsGeneric(stack: ProjectStack): string {
    return `name: CI/CD Pipeline\non:\n  push:\n    branches: [main]\njobs:\n  build:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - run: echo "Add build steps here"\n`;
  }

  private gitlabCI(stack: ProjectStack): string {
    return `# Generated by INA-7 Pro DevOps Agent
stages:
  - lint
  - test
  - build
  - deploy

variables:
  NODE_ENV: test

lint:
  stage: lint
  image: node:22-alpine
  script:
    - npm ci
    - npm run lint

test:
  stage: test
  image: node:22-alpine
  script:
    - npm ci
    - npm test -- --coverage
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  only:
    - main
`;
  }
}
