/**
 * EnvManager.ts — Phase 19 Step 19.5
 * Manage environment variables across dev/staging/prod
 */

import * as fs from 'fs';
import * as path from 'path';
import { Logger } from '../../utils/Logger';

export class EnvManager {
  private root: string;

  constructor(workspaceRoot: string) {
    this.root = workspaceRoot;
  }

  generateExample(): { content: string; keysFound: number } {
    const envContent = this.readFile('.env');
    if (!envContent) return { content: '# No .env file found\n', keysFound: 0 };

    const lines = envContent.split('\n');
    const exampleLines: string[] = ['# Environment variables — copy to .env and fill in values', '# Generated by INA-7 Pro DevOps Agent', ''];
    let keysFound = 0;

    for (const line of lines) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith('#')) {
        exampleLines.push(line);
        continue;
      }
      const match = trimmed.match(/^([A-Z_][A-Z0-9_]*)=(.*)$/i);
      if (match) {
        keysFound++;
        const key = match[1];
        const value = match[2].replace(/^["']|["']$/g, '');
        const hint = this.getHint(key, value);
        exampleLines.push(`${key}=${hint}`);
      } else {
        exampleLines.push(line);
      }
    }

    return { content: exampleLines.join('\n'), keysFound };
  }

  validateEnv(): { missing: string[]; extra: string[]; warnings: string[] } {
    const example = this.readFile('.env.example');
    const env = this.readFile('.env');
    if (!example || !env) return { missing: [], extra: [], warnings: ['No .env or .env.example found'] };

    const exampleKeys = this.extractKeys(example);
    const envKeys = this.extractKeys(env);
    const missing = exampleKeys.filter(k => !envKeys.includes(k));
    const extra = envKeys.filter(k => !exampleKeys.includes(k));
    const warnings: string[] = [];

    if (missing.length > 0) warnings.push(`Missing ${missing.length} required env var(s): ${missing.join(', ')}`);
    if (extra.length > 0) warnings.push(`${extra.length} env var(s) not in .env.example: ${extra.join(', ')}`);

    return { missing, extra, warnings };
  }

  syncCheck(): string {
    const result = this.validateEnv();
    if (result.warnings.length === 0) return 'Environment variables are in sync.';
    return result.warnings.join('\n');
  }

  generateK8sConfigMap(appName: string, namespace: string = 'default'): string {
    const env = this.readFile('.env');
    if (!env) return '';
    const keys = this.extractKeyValues(env);
    const nonSensitive = keys.filter(([k]) => !this.isSensitive(k));
    const data = nonSensitive.map(([k, v]) => `  ${k}: "${v}"`).join('\n');
    return `apiVersion: v1\nkind: ConfigMap\nmetadata:\n  name: ${appName}-config\n  namespace: ${namespace}\ndata:\n${data}\n`;
  }

  generateK8sSecret(appName: string, namespace: string = 'default'): string {
    const env = this.readFile('.env');
    if (!env) return '';
    const keys = this.extractKeyValues(env);
    const sensitive = keys.filter(([k]) => this.isSensitive(k));
    const data = sensitive.map(([k]) => `  ${k}: "CHANGE_ME"`).join('\n');
    return `apiVersion: v1\nkind: Secret\nmetadata:\n  name: ${appName}-secret\n  namespace: ${namespace}\ntype: Opaque\nstringData:\n${data}\n`;
  }

  private extractKeys(content: string): string[] {
    return content.split('\n')
      .map(l => l.trim())
      .filter(l => l && !l.startsWith('#'))
      .map(l => l.split('=')[0]?.trim())
      .filter(Boolean);
  }

  private extractKeyValues(content: string): [string, string][] {
    return content.split('\n')
      .map(l => l.trim())
      .filter(l => l && !l.startsWith('#'))
      .map(l => {
        const idx = l.indexOf('=');
        if (idx < 0) return null;
        return [l.slice(0, idx).trim(), l.slice(idx + 1).trim().replace(/^["']|["']$/g, '')] as [string, string];
      })
      .filter((x): x is [string, string] => x !== null);
  }

  private isSensitive(key: string): boolean {
    const sensitive = ['SECRET', 'PASSWORD', 'KEY', 'TOKEN', 'PRIVATE', 'CREDENTIAL', 'AUTH'];
    return sensitive.some(s => key.toUpperCase().includes(s));
  }

  private getHint(key: string, value: string): string {
    if (this.isSensitive(key)) return '# REQUIRED — sensitive, use secrets manager';
    if (/^\d+$/.test(value)) return `# number, e.g. ${value}`;
    if (/^(true|false)$/i.test(value)) return `# boolean (true/false)`;
    if (value.startsWith('http')) return '# URL';
    if (value.includes('@') || value.includes('://')) return '# connection string';
    return `# e.g. ${value.slice(0, 30)}`;
  }

  private readFile(p: string): string | null {
    try { return fs.readFileSync(path.join(this.root, p), 'utf-8'); } catch { return null; }
  }
}
