/**
 * KubernetesGenerator.ts — Phase 19 Step 19.5
 * Generate Kubernetes manifests: Deployment, Service, Ingress, HPA, etc.
 */

import { ProjectStack, K8sManifest, DevOpsGenerationResult, DevOpsConfig, DEFAULT_DEVOPS_CONFIG } from './DevOpsTypes';

export class KubernetesGenerator {
  private config: DevOpsConfig;

  constructor(config?: Partial<DevOpsConfig>) {
    this.config = { ...DEFAULT_DEVOPS_CONFIG, ...config };
  }

  generate(stack: ProjectStack, appName: string): DevOpsGenerationResult {
    const ns = this.config.k8sNamespace;
    const replicas = this.config.k8sReplicas;
    const port = stack.ports[0] || 3000;
    const files: { name: string; content: string }[] = [];

    files.push({ name: `k8s/namespace.yml`, content: this.namespace(ns) });
    files.push({ name: `k8s/deployment.yml`, content: this.deployment(appName, ns, replicas, port, stack) });
    files.push({ name: `k8s/service.yml`, content: this.service(appName, ns, port) });
    files.push({ name: `k8s/ingress.yml`, content: this.ingress(appName, ns) });
    files.push({ name: `k8s/hpa.yml`, content: this.hpa(appName, ns, replicas) });
    files.push({ name: `k8s/configmap.yml`, content: this.configmap(appName, ns, stack) });
    files.push({ name: `k8s/secret.yml`, content: this.secret(appName, ns) });

    if (stack.databases.includes('postgres')) {
      files.push({ name: `k8s/postgres.yml`, content: this.postgres(ns) });
    }

    files.push({ name: `k8s/kustomization.yml`, content: this.kustomization(files.map(f => f.name.replace('k8s/', ''))) });

    return { type: 'k8s', files, recommendations: [] };
  }

  private namespace(ns: string): string {
    return `apiVersion: v1\nkind: Namespace\nmetadata:\n  name: ${ns}\n`;
  }

  private deployment(app: string, ns: string, replicas: number, port: number, stack: ProjectStack): string {
    return `# Generated by INA-7 Pro DevOps Agent
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${app}
  namespace: ${ns}
  labels:
    app: ${app}
spec:
  replicas: ${replicas}
  selector:
    matchLabels:
      app: ${app}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: ${app}
    spec:
      containers:
        - name: ${app}
          image: ${app}:latest
          ports:
            - containerPort: ${port}
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: ${port}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: ${port}
            initialDelaySeconds: 15
            periodSeconds: 20
          envFrom:
            - configMapRef:
                name: ${app}-config
            - secretRef:
                name: ${app}-secret
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
`;
  }

  private service(app: string, ns: string, port: number): string {
    return `apiVersion: v1\nkind: Service\nmetadata:\n  name: ${app}\n  namespace: ${ns}\nspec:\n  selector:\n    app: ${app}\n  ports:\n    - port: 80\n      targetPort: ${port}\n  type: ClusterIP\n`;
  }

  private ingress(app: string, ns: string): string {
    return `apiVersion: networking.k8s.io/v1\nkind: Ingress\nmetadata:\n  name: ${app}\n  namespace: ${ns}\n  annotations:\n    cert-manager.io/cluster-issuer: letsencrypt-prod\nspec:\n  ingressClassName: nginx\n  tls:\n    - hosts:\n        - ${app}.example.com\n      secretName: ${app}-tls\n  rules:\n    - host: ${app}.example.com\n      http:\n        paths:\n          - path: /\n            pathType: Prefix\n            backend:\n              service:\n                name: ${app}\n                port:\n                  number: 80\n`;
  }

  private hpa(app: string, ns: string, minReplicas: number): string {
    return `apiVersion: autoscaling/v2\nkind: HorizontalPodAutoscaler\nmetadata:\n  name: ${app}\n  namespace: ${ns}\nspec:\n  scaleTargetRef:\n    apiVersion: apps/v1\n    kind: Deployment\n    name: ${app}\n  minReplicas: ${minReplicas}\n  maxReplicas: 10\n  metrics:\n    - type: Resource\n      resource:\n        name: cpu\n        target:\n          type: Utilization\n          averageUtilization: 70\n    - type: Resource\n      resource:\n        name: memory\n        target:\n          type: Utilization\n          averageUtilization: 80\n`;
  }

  private configmap(app: string, ns: string, stack: ProjectStack): string {
    return `apiVersion: v1\nkind: ConfigMap\nmetadata:\n  name: ${app}-config\n  namespace: ${ns}\ndata:\n  NODE_ENV: production\n  PORT: "${stack.ports[0] || 3000}"\n  LOG_LEVEL: info\n`;
  }

  private secret(app: string, ns: string): string {
    return `# IMPORTANT: Replace placeholder values before applying\napiVersion: v1\nkind: Secret\nmetadata:\n  name: ${app}-secret\n  namespace: ${ns}\ntype: Opaque\nstringData:\n  DATABASE_URL: "postgresql://user:password@postgres:5432/app"\n  JWT_SECRET: "CHANGE_ME_IN_PRODUCTION"\n`;
  }

  private postgres(ns: string): string {
    return `apiVersion: apps/v1\nkind: StatefulSet\nmetadata:\n  name: postgres\n  namespace: ${ns}\nspec:\n  serviceName: postgres\n  replicas: 1\n  selector:\n    matchLabels:\n      app: postgres\n  template:\n    metadata:\n      labels:\n        app: postgres\n    spec:\n      containers:\n        - name: postgres\n          image: postgres:16-alpine\n          ports:\n            - containerPort: 5432\n          env:\n            - name: POSTGRES_DB\n              value: app\n            - name: POSTGRES_PASSWORD\n              valueFrom:\n                secretKeyRef:\n                  name: postgres-secret\n                  key: password\n          volumeMounts:\n            - name: pgdata\n              mountPath: /var/lib/postgresql/data\n  volumeClaimTemplates:\n    - metadata:\n        name: pgdata\n      spec:\n        accessModes: [ReadWriteOnce]\n        resources:\n          requests:\n            storage: 10Gi\n---\napiVersion: v1\nkind: Service\nmetadata:\n  name: postgres\n  namespace: ${ns}\nspec:\n  selector:\n    app: postgres\n  ports:\n    - port: 5432\n  clusterIP: None\n`;
  }

  private kustomization(resources: string[]): string {
    return `apiVersion: kustomize.config.k8s.io/v1beta1\nkind: Kustomization\nresources:\n${resources.map(r => `  - ${r}`).join('\n')}\n`;
  }
}
