/**
 * DebtReporter.ts — Phase 20 Step 20.4
 * Generate debt reports in multiple formats
 */

import { DebtItem, DebtBudget, DebtCategory, DebtTrend } from './DebtTypes';

export class DebtReporter {
  generateMarkdown(items: DebtItem[], budget: DebtBudget): string {
    const lines: string[] = [];
    lines.push('# Technical Debt Report');
    lines.push(`Generated: ${new Date().toISOString().split('T')[0]}`);
    lines.push('');
    lines.push('## Summary');
    lines.push(`- **Total items:** ${budget.totalItems}`);
    lines.push(`- **Estimated effort:** ${budget.totalEstimatedHours.toFixed(1)} hours`);
    lines.push(`- **Debt ratio:** ${(budget.debtRatio * 100).toFixed(1)}%`);
    lines.push(`- **Weekly resolved:** ${budget.weeklyBurndown.toFixed(1)}h`);
    lines.push(`- **Weekly added:** ${budget.weeklyAccrual.toFixed(1)}h`);
    lines.push('');
    lines.push('## By Category');
    for (const [cat, count] of Object.entries(budget.byCategory)) {
      if (count > 0) lines.push(`- ${cat}: ${count}`);
    }
    lines.push('');
    lines.push('## Critical Items');
    const critical = items.filter(i => i.severity === 'critical' && i.status === 'open');
    if (critical.length === 0) lines.push('None');
    for (const item of critical) {
      lines.push(`- **${item.title}** — ${item.file}:${item.startLine} (${item.estimatedEffort}h)`);
      lines.push(`  ${item.description}`);
    }
    lines.push('');
    lines.push('## High Priority');
    const high = items.filter(i => i.severity === 'high' && i.status === 'open').slice(0, 10);
    for (const item of high) {
      lines.push(`- ${item.title} — ${item.file}:${item.startLine}`);
    }
    lines.push('');
    lines.push('---');
    lines.push('*Generated by INA-7 Pro Technical Debt Tracker*');
    return lines.join('\n');
  }

  generateJSON(items: DebtItem[], budget: DebtBudget): string {
    return JSON.stringify({ budget, items: items.filter(i => i.status === 'open'), generatedAt: new Date().toISOString() }, null, 2);
  }

  generateWeeklyDigest(items: DebtItem[], trends: DebtTrend[]): string {
    const latest = trends[trends.length - 1];
    if (!latest) return 'No trend data available.';

    const parts: string[] = [];
    parts.push(`## Weekly Debt Digest — ${latest.date}`);
    parts.push('');
    if (latest.netChange < 0) parts.push(`Debt decreased by ${Math.abs(latest.netChange)} items this week.`);
    else if (latest.netChange > 0) parts.push(`Debt increased by ${latest.netChange} items this week.`);
    else parts.push('Debt level unchanged this week.');
    parts.push(`- Resolved: ${latest.resolvedSinceLast}`);
    parts.push(`- New: ${latest.addedSinceLast}`);
    parts.push(`- Total: ${latest.totalItems}`);

    const open = items.filter(i => i.status === 'open');
    const critical = open.filter(i => i.severity === 'critical');
    if (critical.length > 0) parts.push(`\n**Action needed:** ${critical.length} critical item(s) require attention.`);

    return parts.join('\n');
  }

  computeBudget(items: DebtItem[]): DebtBudget {
    const open = items.filter(i => i.status === 'open');
    const byCategory: Record<string, number> = {};
    for (const cat of Object.values(DebtCategory)) byCategory[cat] = 0;
    for (const item of open) byCategory[item.type] = (byCategory[item.type] || 0) + 1;

    return {
      totalItems: open.length,
      byCategory,
      totalEstimatedHours: open.reduce((s, i) => s + i.estimatedEffort, 0),
      weeklyBurndown: 0,
      weeklyAccrual: 0,
      debtRatio: 0,
    };
  }
}
