/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        ina: {
          primary: 'var(--ina-accent-primary, #4f46e5)',
          'primary-hover': 'var(--ina-accent-primary-hover, #4338ca)',
          'primary-text': 'var(--ina-accent-primary-text, #ffffff)',
          secondary: 'var(--ina-accent-secondary, #6366f1)',
          'secondary-hover': 'var(--ina-accent-secondary-hover, #4f46e5)',
          accent: 'var(--ina-accent-primary, #8b5cf6)',
          bg: 'var(--ina-bg-primary)',
          'bg-secondary': 'var(--ina-bg-secondary)',
          'bg-tertiary': 'var(--ina-bg-tertiary)',
          'bg-elevated': 'var(--ina-bg-elevated)',
          'bg-input': 'var(--ina-bg-input)',
          'bg-hover': 'var(--ina-bg-hover)',
          'bg-active': 'var(--ina-bg-active)',
          border: 'var(--ina-border-primary)',
          'border-secondary': 'var(--ina-border-secondary)',
          'border-focus': 'var(--ina-border-focus)',
          'border-error': 'var(--ina-border-error)',
          text: 'var(--ina-text-primary)',
          'text-secondary': 'var(--ina-text-secondary)',
          'text-tertiary': 'var(--ina-text-tertiary)',
          'text-link': 'var(--ina-text-link)',
          success: 'var(--ina-status-success)',
          'success-bg': 'var(--ina-status-success-bg)',
          warning: 'var(--ina-status-warning)',
          'warning-bg': 'var(--ina-status-warning-bg)',
          error: 'var(--ina-status-error)',
          'error-bg': 'var(--ina-status-error-bg)',
          info: 'var(--ina-status-info)',
          'info-bg': 'var(--ina-status-info-bg)',
        },
      },
      fontFamily: {
        sans: ['var(--ina-font-family, var(--vscode-font-family))', 'system-ui', 'sans-serif'],
        mono: ['var(--ina-font-family-code, var(--vscode-editor-font-family))', 'monospace'],
      },
      fontSize: {
        'ina-xs': 'var(--ina-font-size-xs, 11px)',
        'ina-sm': 'var(--ina-font-size-sm, 12px)',
        'ina-md': 'var(--ina-font-size-md, 13px)',
        'ina-lg': 'var(--ina-font-size-lg, 14px)',
        'ina-xl': 'var(--ina-font-size-xl, 16px)',
        'ina-2xl': 'var(--ina-font-size-xxl, 20px)',
      },
      borderRadius: {
        'ina-sm': 'var(--ina-radius-sm, 4px)',
        'ina-md': 'var(--ina-radius-md, 6px)',
        'ina-lg': 'var(--ina-radius-lg, 8px)',
        'ina-xl': 'var(--ina-radius-xl, 12px)',
      },
      spacing: {
        'ina-xs': 'var(--ina-spacing-xs, 2px)',
        'ina-sm': 'var(--ina-spacing-sm, 4px)',
        'ina-md': 'var(--ina-spacing-md, 8px)',
        'ina-lg': 'var(--ina-spacing-lg, 12px)',
        'ina-xl': 'var(--ina-spacing-xl, 16px)',
        'ina-2xl': 'var(--ina-spacing-xxl, 24px)',
        'ina-3xl': 'var(--ina-spacing-xxxl, 32px)',
      },
      transitionDuration: {
        'ina-fast': 'var(--ina-transition-fast, 100ms)',
        'ina-normal': 'var(--ina-transition-normal, 200ms)',
        'ina-slow': 'var(--ina-transition-slow, 300ms)',
      },
    },
  },
  plugins: [],
}
